#pragma once
#include <pebble.h>

#define SPLASH_LOGO_COUNT 9

static const uint32_t s_logo_resources[SPLASH_LOGO_COUNT] = {
  RESOURCE_ID_CONSTELLATION_BW_LOGO_IMAGE,    // 1
  RESOURCE_ID_CONSTELLATION_COLOR_LOGO_IMAGE, // 2
  RESOURCE_ID_HOUSEVARUUN_LOGO_IMAGE,         // 3
  RESOURCE_ID_FREESTAR_LOGO_IMAGE,            // 4
  RESOURCE_ID_SYSDEF_LOGO_IMAGE,              // 5
  RESOURCE_ID_CRIMSON_LOGO_IMAGE,             // 6
  RESOURCE_ID_MOON_BACKGROUND_IMAGE,          // 7
  RESOURCE_ID_TRACKER_ALLIANCE_BW_LOGO_IMAGE, // 8
  RESOURCE_ID_TRACKER_ALLIANCE_COLOR_LOGO_IMAGE // 9
};